name: C/C++ CI
on: push
jobs:
  x86_build:
    name: Build on ${{ matrix.os }}
    strategy:
        matrix:
          cc: [ gcc ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build srsLTE on x86
        run: |
          apt update
          apt install -y build-essential cmake libfftw3-dev libmbedtls-dev libpcsclite-dev libboost-program-options-dev libconfig++-dev libsctp-dev colordiff ninja-build
          mkdir build && cd build && cmake -GNinja .. && ninja && ctest -T memcheck
    
  aarch64_build:
    runs-on: ubuntu-18.04
    name: Build and test on aarch64
    steps:
    - name: Build srsLTE on aarch64
      uses: uraimo/run-on-arch-action@master
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: |
          apt update
          apt install -y build-essential cmake libfftw3-dev libmbedtls-dev libpcsclite-dev libboost-program-options-dev libconfig++-dev libsctp-dev colordiff ninja-build
          mkdir build && cd build && cmake -GNinja .. && ninja && ctest -T memcheck
